#!/bin/bash

cp -r ./*.* ~/
cp -r ./cron.d/* /etc/cron.d/

sudo apt-get install pylint

git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline
git clone git://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive
